
[functions.resolve-google-maps-link]
enabled = true
verify_jwt = false
import_map = "./functions/resolve-google-maps-link/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resolve-google-maps-link/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resolve-google-maps-link/*.html" ]

[functions.send-venue-request-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-venue-request-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-venue-request-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-venue-request-email/*.html" ]

[functions.send-venue-approval-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-venue-approval-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-venue-approval-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-venue-approval-email/*.html" ]

[functions.app-get-venue-analytics]
enabled = true
verify_jwt = false
import_map = "./functions/app-get-venue-analytics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/app-get-venue-analytics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/app-get-venue-analytics/*.html" ]
